// <auto-generated />
using CaisseEnregistreuse.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaisseEnregistreuse.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CaisseEnregistreuse.NET.Models.Carte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageCarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteEnStock")
                        .HasColumnType("int");

                    b.Property<int>("TypeDeCarteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeDeCarteId");

                    b.ToTable("Cartes");
                });

            modelBuilder.Entity("CaisseEnregistreuse.NET.Models.TypeDeCarte", b =>
                {
                    b.Property<int>("TypeDeCarteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeDeCarteId"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TypeDeCarteId");

                    b.ToTable("TypeDeCartes");
                });

            modelBuilder.Entity("CaisseEnregistreuse.NET.Models.Carte", b =>
                {
                    b.HasOne("CaisseEnregistreuse.NET.Models.TypeDeCarte", "TypeDeCarte")
                        .WithMany("ListeCartes")
                        .HasForeignKey("TypeDeCarteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDeCarte");
                });

            modelBuilder.Entity("CaisseEnregistreuse.NET.Models.TypeDeCarte", b =>
                {
                    b.Navigation("ListeCartes");
                });
#pragma warning restore 612, 618
        }
    }
}
